export const AUTHENTICATE = 'auth/AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'auth/AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'auth/AUTHENTICATE_FAILURE';

export const AUTHORIZE = 'auth/AUTHORIZE';
export const AUTHORIZE_SUCCESS = 'auth/AUTHORIZE_SUCCESS';
export const AUTHORIZE_FAILURE = 'auth/AUTHORIZE_FAILURE';

export const ORGANIZATION_PASSWORD_CONFIRM_SUCCESS =
  'auth/ORGANIZATION_PASSWORD_CONFIRM_SUCCESS';

export const DEAUTHORIZE = 'auth/DEAUTHORIZE';
